config/routes.rb
Rails.application.routes.draw do
root 'home#index'

namespace :admin do
  resources :users
end

get 'profile', to: 'users#show'
get 'profile/edit', to: 'users#edit'
delete 'profile', to: 'users#destroy'

resources :courses, :events, :books, :users
resource :session, only: %i[new create destroy]

get 'book/sort', to: 'books#sort'
get 'course/sort', to: 'courses#sort'
get 'event/sort', to: 'events#sort'
get 'admin/sort', to: 'admin/users#sort'

resources :courses_users, only: %i[show destroy]

resources :translations, only: %i[index]
post 'translations/translate', as: :translate

resources :tests, only: %i[index]

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_and_belongs_to_many :courses

  has_one_attached :avatar

  validates :name, :surname, :age, :login, presence: :true
  validates :login, uniqueness: true
  validates :password, confirmation: true
  validates :age, numericality: {only_integer: true, greater_than: 0}
  validates :name, :surname, format: {with: /\A[a-zA-Z]+\z/}

  enum role: %i[student teacher admin]
end

app/controllers/admin/users_controller.rb
  class Admin::UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]
    before_action :authorize_user
    after_action :verify_authorized

    def index
      query = params[:query]
      if query.nil?
        @users = User.all
      else
        @users = User.where(login: query)

        if @users.empty?
          flash.now[:notice] = 'По вашему запросу ничего не найдено...'
        end
      end
    end

    def show
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      if @user.valid?
        @user.teacher!
      end

      if @user.save
        redirect_to admin_users_path, notice: 'Преподаватель успешно зарегистрирован!'
      else
        flash.now[:alert] = 'Вы неправильно заполнили поля формы!'

        render :new
      end
    end

    def edit
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path, notice: 'Пользователь отредактирован!'
      else
        flash.now[:alert] = 'Вы неправильно заполнили поля формы!'

        render :edit
      end
    end

    def destroy
      if @user.admin?
        redirect_to admin_user_path, alert: 'Вы не можете удалить админа'
      else
        @user.destroy
        redirect_to admin_users_path, notice: 'Пользователь удалён!'
      end
    end

    def sort
      @users = User.order(:login)

      render "index"
    end

    private

    def user_params
      params.require(:user).permit(:name, :surname, :age, :login, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def authorize_user
      authorize([:admin, (@user || User)])
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user
  after_action :verify_authorized

  def index
    @users = User.all
  end

  def show
    @courses = @user.courses
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.valid?
      @user.student!
    end

    if @user.save
      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации!'

      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to '/profile', notice: 'Данные пользователя обновлены!'
    else
      flash.now[:alert] = 'При обновлении данных возникли ошибки!'

      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён!'
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :surname, :age, :login, :password)
  end

  def set_user
    @user = current_user
  end

  def authorize_user
    authorize(@user || User)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <p class="icon"><%= link_to fa_icon('arrow-left'), :back %></p>

  <h2 class="title-lg mb mt">Редактирование пользователя</h2>

  <%= form_with model: @user, html: { multipart: true } do |form| %>

    <p class="mt"><%= form.label :avatar, 'Фото профиля' %></p>
    <p><%= form.file_field :avatar, class: 'text-lg' %></p>

    <p class="mt"><%= form.label :name, 'Имя' %></p>
    <p><%= form.text_field :name, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :surname, 'Фамилия' %></p>
    <p><%= form.text_field :surname, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:surname).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :age, 'Возраст' %></p>
    <p><%= form.number_field :age, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:age).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :login, 'Логин' %></p>
    <p><%= form.text_field :login, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:login).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :password, 'Пароль' %></p>
    <p><%= form.password_field :password, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="text-sm"><%= fa_icon('exclamation') %> Если не хотите менять пароль - оставьте это поле пустым</p>

    <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
    <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="text-sm"><%= fa_icon('exclamation') %> Если не хотите менять пароль - оставьте это поле пустым</p>

    <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">

  <h2 class="title-lg mb">Регистрация</h2>

  <%= form_with model: @user, data: {turbo: false} do |form| %>
    <p><%= form.label :name, 'Имя' %></p>
    <p><%= form.text_field :name, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :surname, 'Фамилия' %></p>
    <p><%= form.text_field :surname, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:surname).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :age, 'Возраст' %></p>
    <p><%= form.number_field :age, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:age).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :login, 'Логин' %></p>
    <p><%= form.text_field :login, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:login).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :password, 'Пароль' %></p>
    <p><%= form.password_field :password, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
    <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
    <% end %>

    <p class="mt-lg"><%= form.submit 'Зарегистрироваться', class: 'button button-main' %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<%= javascript_tag 'test.js'%>

<div class="container">

  <div class="mb-sm">
    <div class="text-right">
      <p class="mt icon"><%= link_to fa_icon('edit'), profile_edit_path, title: 'Редактировать профиль' %></p>

      <p class="mt ml icon">
        <%= link_to fa_icon('trash'), profile_path, data: {
          turbo_method: :delete,
          turbo_confirm: "Вы уверены, что хотите удалить профиль?"
        }, title: 'Удалить профиль' %>
      </p>
    </div>

    <%= image_tag @user.avatar.variant(resize_to_fill: [225, 225]) if @user.avatar.attached? %>

    <p class="title mt"><%= "Логин: #{@user.login}" %></p>
  </div>

  <div class="item-footer">
    <p class="mt text-lg"><%= "Имя: #{@user.name}" %></p>
    <p class="mt text-lg"><%= "Фамилия: #{@user.surname}" %></p>
    <p class="mt text-lg"><%= "Возраст: #{@user.age}" %></p>
  </div>

  <%= link_to 'Пройти тест на знание английского', tests_path, class: 'button button-main mt' %>

</div>

<div class="container mt">
  <p class="title-lg mt mb">Мои курсы</p>

  <div class="item-container">
    <% @courses.each do |course| %>
      <div class="item mb">

        <div class="text-right">
            <p class="mt ml icon">
              <%= link_to fa_icon('trash'), courses_user_path(course), data: {
                turbo_method: :delete,
                turbo_confirm: "Вы уверены, что хотите удалить курс?"
              }, title: 'Удалить' %>
            </p>
        </div>

        <p class="text-bold"><%= "Название: #{course.name}" %></p>

        <div class="item-footer">
          <p class="mt-sm"><%= "Язык изучения: #{course.language}" %></p>
          <p class="mt-sm"><%= "Цена: #{course.price}" %></p>
        </div>

      </div>
    <% end %>
  </div>

</div>