config/routes.rb
Rails.application.routes.draw do
root 'home#index'

namespace :admin do
  resources :users
end

get 'profile', to: 'users#show'
get 'profile/edit', to: 'users#edit'
delete 'profile', to: 'users#destroy'

resources :courses, :events, :books, :users
resource :session, only: %i[new create destroy]

get 'book/sort', to: 'books#sort'
get 'course/sort', to: 'courses#sort'
get 'event/sort', to: 'events#sort'
get 'admin/sort', to: 'admin/users#sort'

resources :courses_users, only: %i[show destroy]

resources :translations, only: %i[index]
post 'translations/translate', as: :translate

resources :tests, only: %i[index]

end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date, :time, :place, :language, :description, presence: true
  validates :language, length: {minimum: 2}, format: {with: /\A[a-zA-Z]+\z/}

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authorize_event
  after_action :verify_authorized

  def index
    query = params[:query]
    if query.nil?
      @events = Event.all
    else
      @events = Event.where(name: query)

      if @events.empty?
        flash.now[:notice] = 'По вашему запросу ничего не найдено...'
      end
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Новое мероприятие добавлено!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы!'

      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Мероприятие отредактировано!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы!'

      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path, notice: 'Мероприятие удалено!'
  end

  def sort
    @events = Event.order(:name)

    render "index"
  end

  private
  def event_params
    params.require(:event).permit(:name, :date, :time, :place, :language, :description)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def authorize_event
    authorize(@event || Event)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>

<div>
  <p><%= form.label :name, 'Название' %></p>
  <p><%= form.text_field :name, class: 'form-text-field' %></p>
  <% event.errors.full_messages_for(:name).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :date, 'Дата проведения' %></p>
  <p><%= form.date_field :date, class: 'form-text-field' %></p>
  <% event.errors.full_messages_for(:date).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :time, 'Время проведения' %></p>
  <p><%= form.time_field :time, class: 'form-text-field' %></p>
  <% event.errors.full_messages_for(:time).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :place, 'Место проведения' %></p>
  <p><%= form.text_field :place, class: 'form-text-field' %></p>
  <% event.errors.full_messages_for(:place).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :language, 'Язык изучения' %></p>
  <p><%= form.text_field :language, class: 'form-text-field' %></p>
  <% event.errors.full_messages_for(:language).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :description, 'Описание' %></p>
  <p><%= form.text_area :description, class: 'form-text-area' %></p>
  <% event.errors.full_messages_for(:description).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>
</div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <p class="icon"><%= link_to fa_icon('arrow-left'), :back %></p>
  <h3 class="title-lg mb mt">Редактирование мероприятия</h3>

  <%= render "form", event: @event %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="text-right">
    <%= form_with method: :get do |form| %>
      <%= form.label :query, 'Поиск', class: 'title-sm' %>
      <%= form.text_field :query, placeholder: 'Введите название', class: 'form-text-field' %>
      <%= form.submit 'Искать', class: 'button button-main' %>
    <% end %>
  </div>

  <h2 class="title-lg mb">Наши мероприятия  <%= link_to fa_icon('sort-down'), event_sort_path %></h2>

  <div class="item-container">
    <% @events.each do |event| %>
      <div class="item mb">

        <div class="text-right">
          <p class="icon"><%= link_to fa_icon('info-circle'), event %></p>
        </div>

        <p class="text-bold"><%= "Название: #{event.name}" %></p>

        <div class="item-footer">
          <p class="mt-sm"><%= "Дата проведения: #{l event.date, format: :short}" %></p>
          <p class="mt-sm"><%= "Язык изучения: #{event.language}" %></p>
        </div>

      </div>
    <% end %>
  </div>

  <% if policy(:event).new? %>
    <p class="mt"><%= link_to 'Добавить мероприятие', new_event_path, class: 'button button-main' %></p>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container">
  <p class="icon"><%= link_to fa_icon('arrow-left'), :back %></p>
  <h3 class="title-lg mb mt">Добавление мероприятия</h3>

  <%= render "form", event: @event %>
</div>

app/views/events/show.html.erb
<div class="container">

  <p class="icon"><%= link_to fa_icon('arrow-left'), :back %></p>

  <div class="mb-sm">
    <div class="text-right">
      <% if policy(@event).edit? %>
        <p class="mt icon"><%= link_to fa_icon('edit'), edit_event_path(@event), title: 'Редактировать' %></p>
      <% end%>

      <% if policy(@event).destroy? %>
        <p class="mt ml icon">
          <%= link_to fa_icon('trash'), event_path(@event), data: {
            turbo_method: :delete,
            turbo_confirm: "Вы уверены, что хотите удалить мероприятие?"
          }, title: 'Удалить' %>
        </p>
      <% end %>
    </div>

    <p class="title"><%= "Название: #{@event.name}" %></p>
  </div>

  <div class="item-footer">
    <p class="mt text-lg"><%= "Дата проведения: #{l @event.date, format: :short}" %></p>
    <p class="mt text-lg"><%= "Время проведения: #{l @event.time, format: :short}" %></p>
    <p class="mt text-lg"><%= "Место проведения: #{@event.place}" %></p>
    <p class="mt mb text-lg"><%= "Язык изучения: #{@event.language}" %></p>
    <label class="mt text-lg">Описание</label>
    <textarea class="form-text-area mt-sm" disabled><%= @event.description %></textarea>
  </div>

</div>