config/routes.rb
Rails.application.routes.draw do
root 'home#index'

namespace :admin do
  resources :users
end

get 'profile', to: 'users#show'
get 'profile/edit', to: 'users#edit'
delete 'profile', to: 'users#destroy'

resources :courses, :events, :books, :users
resource :session, only: %i[new create destroy]

get 'book/sort', to: 'books#sort'
get 'course/sort', to: 'courses#sort'
get 'event/sort', to: 'events#sort'
get 'admin/sort', to: 'admin/users#sort'

resources :courses_users, only: %i[show destroy]

resources :translations, only: %i[index]
post 'translations/translate', as: :translate

resources :tests, only: %i[index]

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy buy delete_users_course]
  before_action :authorize_course
  after_action :verify_authorized

  def index
    query = params[:query]
    if query.nil?
      @courses = Course.all
    else
      @courses = Course.where(name: query)

      if @courses.empty?
        flash.now[:notice] = 'По вашему запросу ничего не найдено...'
      end
    end
  end


  def show
  end


  def new
    @course = Course.new
  end


  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: 'Новый курс добавлен!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы!'

      render :new, status: :unprocessable_entity
    end
  end


  def edit
  end


  def update
    if @course.update(course_params)
      redirect_to @course,  notice: 'Курс отредактирован!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы!'

      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @course.destroy

    redirect_to courses_path, notice: 'Курс удалён!'
  end

  def sort
    @courses = Course.order(:name)

    render "index"
  end


  def buy
    current_user.courses<< @course

    redirect_to courses_path, notice: 'Курс куплен!'
  end

  def delete_users_course
    current_user.courses.delete(@course)

    redirect_to '/profile', notice: 'Курс удалён!'
  end





  private

  def course_params
    params.require(:course).permit(:name, :language, :level, :quantity_of_students, :age_of_group, :price, :description)
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def authorize_course
    authorize(@course || Course)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with model: course do |form| %>

<div>
  <p><%= form.label :name, 'Название' %></p>
  <p><%= form.text_field :name, class: 'form-text-field' %></p>
  <% course.errors.full_messages_for(:name).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :language, 'Язык изучения' %></p>
  <p><%= form.text_field :language, class: 'form-text-field' %></p>
  <% course.errors.full_messages_for(:language).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :level, 'Уровень языка' %></p>
  <p><%= form.text_field :level, class: 'form-text-field' %></p>
  <% course.errors.full_messages_for(:level).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :quantity_of_students, 'Количество студентов в группе' %></p>
  <p><%= form.number_field :quantity_of_students, class: 'form-text-field' %></p>
  <% course.errors.full_messages_for(:quantity_of_students).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :age_of_group, 'Средний возраст группы' %></p>
  <p><%= form.number_field :age_of_group, class: 'form-text-field' %></p>
  <% course.errors.full_messages_for(:age_of_group).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :price, 'Цена' %></p>
  <p><%= form.number_field :price, class: 'form-text-field' %></p>
  <% course.errors.full_messages_for(:price).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.label :description, 'Описание' %></p>
  <p><%= form.text_area :description, class: 'form-text-area' %></p>
  <% course.errors.full_messages_for(:description).each do |message| %>
    <p class="mt-sm text-red "><%= fa_icon('exclamation-triangle') + ' ' + message %></p>
  <% end %>
</div>

<div>
  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>
</div>

<% end %>

app/views/courses/edit.html.erb
<div class="container">
  <p class="icon"><%= link_to fa_icon('arrow-left'), :back %></p>
  <h3 class="title-lg mb mt">Редактирование курса</h3>

  <%= render "form", course: @course %>
</div>

app/views/courses/index.html.erb
<div class="container">
  <div class="text-right">
    <%= form_with method: :get do |form| %>
      <%= form.label :query, 'Поиск', class: 'title-sm' %>
      <%= form.text_field :query, placeholder: 'Введите название', class: 'form-text-field' %>
      <%= form.submit 'Искать', class: 'button button-main' %>
    <% end %>
  </div>

  <h2 class="title-lg mb">Наши курсы  <%= link_to fa_icon('sort-down'), course_sort_path %></h2>

  <div class="item-container">
    <% @courses.each do |course| %>
      <div class="item mb">

        <div class="text-right">
          <p class="icon"><%= link_to fa_icon('info-circle'), course %></p>
        </div>

        <p class="text-bold"><%= "Название: #{course.name}" %></p>

        <div class="item-footer">
          <p class="mt-sm"><%= "Язык изучения: #{course.language}" %></p>
          <p class="mt-sm"><%= "Цена: #{course.price}" %></p>
        </div>

      </div>
    <% end %>
  </div>

  <% if policy(:course).new? %>
    <p class="mt"><%= link_to 'Добавить курс', new_course_path, class: 'button button-main' %></p>
  <% end %>
</div>

app/views/courses/new.html.erb
<div class="container">
  <p class="icon"><%= link_to fa_icon('arrow-left'), :back %></p>
  <h3 class="title-lg mb mt">Добавление курса</h3>

  <%= render "form", course: @course %>
</div>

app/views/courses/show.html.erb
<div class="container">

  <p class="icon"><%= link_to fa_icon('arrow-left'), :back %></p>

  <div class="mb-sm">
    <div class="text-right">
      <% if policy(@course).edit? %>
        <p class="mt icon"><%= link_to fa_icon('edit'), edit_course_path(@course), title: 'Редактировать' %></p>
      <% end %>

      <% if policy(@course).destroy? %>
        <p class="mt ml icon">
          <%= link_to fa_icon('trash'), course_path(@course), data: {
            turbo_method: :delete,
            turbo_confirm: "Вы уверены, что хотите удалить курс?"
          }, title: 'Удалить' %>
        </p>
      <% end %>
    </div>

    <p class="title mt"><%= "Название: #{@course.name}" %></p>
  </div>

  <div class="item-footer">
    <p class="mt text-lg"><%= "Язык изучения: #{@course.language}" %></p>
    <p class="mt text-lg"><%= "Уровень языка: #{@course.level}" %></p>
    <p class="mt text-lg"><%= "Количество студентов в группе: #{@course.quantity_of_students}" %></p>
    <p class="mt text-lg"><%= "Средний возраст группы: #{@course.age_of_group}" %></p>
    <p class="mt mb text-lg"><%= "Цена: #{@course.price}" %></p>
    <label class="mt text-lg">Описание</label>
    <textarea class="form-text-area mt-sm" disabled><%= @course.description %></textarea>
  </div>

  <p><%= link_to 'Купить курс', courses_user_path(@course), class: 'button button-main mt' %></p>

</div>